### ISSUE TITLE
为什么没有备份功能？

### ISSUE THREAD

**Issue by ztjal** [bigsinger/AndroidIdChanger#1]
改这些东西想到的第一件事就是备份啊，竟然没有...

**Comment by bigsinger** [comment]
无需备份

**Comment by trulymark** [comment]
有个问题啊，在XPOSED勾选后重启依然提示未在XPOSED中启用。求解

**Comment by lars18th** [comment]
Hi @bigsinger ,

I found the option for a backup of the "phoneinfo.xml" very useful. For example, you can try to hook with different values from different devices.

I suggest a simple support for doing this manually.
Futhermore, the support for "auto backup" will be great. See:
https://developer.android.com/guide/topics/data/autobackup.html
You only need to add to the AndroidManifest.xml file:
```
<application ...
    android:allowBackup="true">
</app>
```

You agree?

**Comment by lars18th** [comment]
Hi @bigsinger,

I see the changes in v.1.19. Thank you!
"android:allowBackup="true"" is included, and the export of HTM with the device info is great! :smile:

However, for getting the "mydevice.htm" file you need root access. I suggest to export the file to the SDCard. In the path "/sdcard/changer-mydevice.htm" (this is the internal emulated path present in all recent device from KitKat).

Futhermore, perhaps you should want also to export "changer-hooked.htm" with the hooked values.

Regards!

**Comment by bigsinger** [comment]
gooood idea :+1:

**Comment by bigsinger** [comment]
public void onClick(DialogInterface dialog, int which) {
                                            Intent intent = new Intent();
                                            intent.setAction(Intent.ACTION_SEND);
                                            intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                                            intent.addCategory("android.intent.category.DEFAULT");
                                            Uri uri = Uri.fromFile(file);

                                            intent.putExtra(Intent.EXTRA_SUBJECT, Constant.TAG);
                                            intent.putExtra(Intent.EXTRA_STREAM, uri);
                                            //intent.setType("application/html");

                                            intent.setType("text/html");    //text/plain text/html
                                            String aEmailList[] = {recvMail};
                                            intent.putExtra(android.content.Intent.EXTRA_EMAIL, aEmailList);
                                            intent.putExtra(Intent.EXTRA_TEXT, SettingActivity.getDeviceInfoText(MainActivity.this));
                                            intent.putExtra(Intent.EXTRA_HTML_TEXT, htmlDeviceInfo);
                                            if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
                                                intent.putExtra(Intent.EXTRA_HTML_TEXT, htmlDeviceInfo);
                                            }
                                            try {
                                                startActivity(Intent.createChooser(intent, file.getName()));
                                            } catch (Exception e) {
                                                e.printStackTrace();
                                            }
                                        }



@lars18th  EXTRA_HTML_TEXT not working, any idea?

**Comment by lars18th** [comment]
Hi @bigsinger ,

I tested this in v1.20 and I see that I only receive in after the share an URL with "htp://..." content (with the IP address of the device).

So the problem is the parameters you fill in the intent. I feel you like to share the contect of the file, and not the URI of the file, right? Then, please see this simple example:
https://github.com/HaxeExtension/extension-share/blob/master/java/ShareEx/project/android/shareex/ShareEx.java#L18

As I feel, your code trys to create an intent with an E-Mail envelope. In this case, the TYPE needs to be MIME and a composed E-mail. Then you can put the SENDER, RECEIVER, File Attachment, etc. In the way of this: https://stackoverflow.com/a/3300495

However, I feel it's more simple to share the HTML content directly.
So the code can be something like:

```
public void onClick(DialogInterface dialog, int which) {
   Intent intent = new Intent();
   intent.setAction(Intent.ACTION_SEND);
   intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
   intent.addCategory("android.intent.category.DEFAULT");
   Uri uri = Uri.fromFile(file);

   intent.putExtra(Intent.EXTRA_SUBJECT, Constant.TAG);
   intent.putExtra(Intent.EXTRA_STREAM, uri);
   //intent.setType("application/html");

   intent.setType("text/html");    //text/plain text/html
   String aEmailList[] = {recvMail};
   intent.putExtra(android.content.Intent.EXTRA_EMAIL, aEmailList);
   intent.putExtra(Intent.EXTRA_TEXT, SettingActivity.getDeviceInfoText(MainActivity.this));
   intent.putExtra(Intent.EXTRA_STREAM, uri);
   try {
      startActivity(Intent.createChooser(intent, file.getName()));
   } catch (Exception e) {
      e.printStackTrace();
   }
}
```

Please, check it!

**Comment by bigsinger** [comment]
i want send info with html format.   EXTRA_TEXT can only send pure text without format.

i tried EXTRA_HTML_TEXT, but not work

**Comment by lars18th** [comment]
Hi @bigsinger ,

When sending HTML the "EXTRA_TEXT" and "EXTRA_HTML_TEXT" are both used.
However, as you like to **read** the content of the "uri" file, you only need to attach the "uri" to the "EXTRA_STREAM". Then, the Android will put the content inside the EXTRA_HTML_TEXT because it's empty prior to send the Intent. Or this is that I understand.

I hope it helps!

Note: For a simple test, write a simple hardcoded HTML in the Intent (only for your internal checking). Another example code here:

```
void sendFileByMail(Uri filelocation, String to[], String fileOut) {
    //String filelocation="/mnt/sdcard/contacts_sid.vcf";  
    String pathname = Environment.getExternalStorageDirectory()
            .getAbsolutePath();

    //  Create a new file by

    File myfile = new File(pathname + "/hexasense/fr", fileOut);//"ImageList.txt");//"vache.jpg");//"ImageList.txt");

    Intent emailIntent = new Intent(Intent.ACTION_SEND);
    // set the type to 'email'
    emailIntent.setType("vnd.android.cursor.dir/email");
    //String to[] = {"asd@gmail.com"};
    emailIntent.putExtra(Intent.EXTRA_EMAIL, to);
    // the attachment
    //emailIntent .putExtra(Intent.EXTRA_STREAM, filelocation);

    emailIntent.putExtra(Intent.EXTRA_STREAM, Uri.fromFile(myfile));
    // the mail subject
    emailIntent.putExtra(Intent.EXTRA_SUBJECT,
            "vEsperanto Validated Image List");
    /*<IMG SRC="url_de_l_image"
         ALT="Texte remplaant l'image"
         TITLE="Texte  afficher">
         https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS-wGMynDn2HkOTHUGgcyRLVHYbtiuzt0m8ziNT5P9ZELTyQewYehKWtJyp
                
         <IMG SRC="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS-wGMynDn2HkOTHUGgcyRLVHYbtiuzt0m8ziNT5P9ZELTyQewYehKWtJyp"
         ALT="Texte remplaant l'image"
         TITLE="Texte  afficher">
         "<html><head></head><body>";
    $message .= "<img src='link-image.jpg' alt='' /></body></html>";
                 
                 
     */
    emailIntent.putExtra(Intent.EXTRA_TEXT, "image gj");// +"<html><head></head><body><IMG SRC=\"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS-wGMynDn2HkOTHUGgcyRLVHYbtiuzt0m8ziNT5P9ZELTyQewYehKWtJyp\"/></body></html>");

    emailIntent
            .putExtra(
                    Intent.EXTRA_HTML_TEXT,
                    "image "
                            + "<IMG SRC=\"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS-wGMynDn2HkOTHUGgcyRLVHYbtiuzt0m8ziNT5P9ZELTyQewYehKWtJyp\">");
    String body = "azert"
            + "<html><head></head>"
            + "<body>ool raoul c"
            + "<IMG SRC=\"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS-wGMynDn2HkOTHUGgcyRLVHYbtiuzt0m8ziNT5P9ZELTyQewYehKWtJyp\""
            + " ALT=\"trerterte\" " + " TITLE=\"Texte  afficher\" "
            + ">" + "    dfghjk " + "</body></html>";//"<html>something</html>";
    //emailIntent.putExtra(Intent.EXTRA_TEXT, Html.fromHtml(body));
    body = body + "     " + "Send from phone build" + readPhoneBuild()
            + " \n " + readPackageInfo("com.google.android.tts")
            + " \n " + readPackageInfo("");
    emailIntent.putExtra(Intent.EXTRA_TEXT, "image gj" + body);
    startActivity(Intent.createChooser(emailIntent, "Send email..."));
}
```

**Comment by bigsinger** [comment]
i want to get the device info by two ways.
if no email was set on some device, we can also send the 'mydevice.htm' file with other app.
if email was set, we can send html format text info directly

and my code can send both file and text, but the text is  just pure text.
if  we can both send file and html text, it's great.

you agree?

**Comment by lars18th** [comment]
> I want to get the device info by two ways.
> you agree?

:+1: 

However, please use different commands for each operation. Perhaps the best is one unique menu entry ("Share"), and inside it a selection for different activities: "Send by email", "Share with...", etc.

You agree?

Note: If you can't share now in HTML, try first to share as plain text.

**Comment by bigsinger** [comment]
:+1:
