### ISSUE TITLE
Add support per App context

### ISSUE THREAD

**Issue by lars18th** [bigsinger/AndroidIdChanger#11]
Hi,

I like to use this module for changing ID info for only one specific App, not at the entire global environment.

Please, can this do it?
Thank you!

**Comment by bigsinger** [comment]
the version 1.7 surpports this

**Comment by lars18th** [comment]
> the version 1.7 surpports this
Great!

And this version supports Android Nougat?

**Comment by bigsinger** [comment]
xposed can support Android Nougat?

**Comment by lars18th** [comment]
> xposed can support Android Nougat?
Sure! Last version Xposed API v88.x supports Android 7.0 Nougat.
See http://forum.xda-developers.com/showthread.php?t=3034811

**Comment by bigsinger** [comment]
i have no Android N device, can you install the XposedInstaller_3.1.2.apk to test?

in my gradle file:
compile 'de.robv.android.xposed:api:82:sources'

need i upgrade it?

**Comment by lars18th** [comment]
Hi,

Regarding Nougat support I'll move to #14 ...

**Comment by noobfish** [comment]
I'M using AOSP Android Nougat,the APP works !Thank you developer !
