### ISSUE TITLE
Core: Additional ID data

### ISSUE THREAD

**Issue by lars18th** [bigsinger/AndroidIdChanger#12]
Hi,

Please, can you add other useful info?

- Manufacturer Name
- Model Name
- Hardware Name
- Board Name
- Product Name
- Brand Name
- Manufacturer Device Name
- Bootloader Name

Thank you!

**Comment by bigsinger** [comment]
these all supported:
Manufacturer Name
Model Name
Hardware Name
Board Name
Product Name
Brand Name
Manufacturer Device Name

only "Bootloader Name" is not supported now, but it will be next version.

**Comment by lars18th** [comment]
> only "Bootloader Name" is not supported now, but it will be next version.
Good!

So, I'll prepare a list of another interesting values not already included, if you like to include them as well.

Regards!

**Comment by bigsinger** [comment]
ok, show me

**Comment by lars18th** [comment]
Hi,

I copy here only for reference... Already missing values:

- Build.BOOTLOADER
- Build.RADIO
- Build.TAGS
- Build.TIME
- Build.TYPE
- Build.VERSION.CODENAME
- Build.VERSION.SDK

**Comment by lars18th** [comment]
Hi,

Please, can you add these values too?
It's quite easy as all of these values are in the Build class. So the same code as FINGERPRINT or DISAPLAY.

Regards!

**Comment by bigsinger** [comment]
Build.RADIO & Build.VERSION.SDK are deprecated!!!

**Comment by lars18th** [comment]
> Build.RADIO & Build.VERSION.SDK are deprecated!!!

Ok, so not include it. I copied these values from another ancient project. The idea is to support all values as we can. :smile:

**Comment by bigsinger** [comment]
i wonder is it necessary for these values?

Build.TAGS
Build.TIME
Build.TYPE
Build.VERSION.CODENAME

**Comment by lars18th** [comment]
> i wonder is it necessary for these values?

As it's easy to add to the App, why not? :smile: 

Remember: when you will add the option to save null values in the preferences (for not hook these values) the user will have the option for determining which values hook and what not. The decision are responsability of the user. The idea is incorporate as much values as we can.

**Comment by lars18th** [comment]
Hi,

In the v1.13 I see new values in the UI. However, I don't see them in the "phoneinfo.xml" file.
So, I list here these values, and some examples for the "hardcoded" value (as they are empty now):

```
Build.TAGS:   "release-keys"
Build.TIME:   "1429649372000"
Build.TYPE:   "user"
Build.VERSION.CODENAME:  "REL"
IP:           "192.168.1.100"
Google Ad ID: "38400000-8cf0-11bd-b23e-10b96e40000d"
```

Futhermore, I feel that some more values are missing the the hook() function. Please, revise the src file for supporting all the values!

**Comment by bigsinger** [comment]
ok,maybe next version.

**Comment by lars18th** [comment]
> ok,maybe next version.

Sure! As I see some values in the UI that doesn't have the corresponding hook in the source.

Futhermore, please put more descriptive info in the UI about the values. For example, put "Build.TAGS" instead of "TAGS" as it's more informative. For example, when I see "user" I'm not sure about the value (it's the Android user, it's the build.prop "ro.build.user", etc.).

Thank you for your work! This module is going to success!

**Comment by bigsinger** [comment]
:+1:  ok

**Comment by lars18th** [comment]
Hi @bigsinger ,

In v1.14 the UI is improved. I see all the values with the correct name. Great!

However, in the Logs I see only a limited number of values hook. Please, can you add all the values that appear in the UI to the source?
Futhermore, please upgrade the src file to the last version (if you can).

Regards!

**Comment by lars18th** [comment]
Hi @bigsinger ,

In "Original" and "After" lists the **order** is different. Check the position of the "Board" value in both lists.

**Comment by lars18th** [comment]
Hi @bigsinger ,

> In "Original" and "After" lists the order is different. Check the position of the "Board" value in both lists.

In version v.1.15 this bug continues. Please, change between "Original" and "After" when showing "Build.TYPE" in the middle of the screen and check that values are in different order! (mainly because the different position of "Board" value).

Regards!

**Comment by bigsinger** [comment]
ok

**Comment by lars18th** [comment]
Hi @bigsinger ,

In the current src file I see that some of the current values in the UI and preferences aren't used.
I list here the missing values in the source:

- googlead_id
- IP
- NetType
- NetworkOperatorName
- BootLoader
- Resolution
- RadioVersion
- Width
- SimSerialNo
- Height

If you don't know how to hook these values, I suggest to grey them in the IU (this will indicate that the current implementation doesn't change them). Also you can include them in the code and print in the log " not implemented " until you can hook them.

However, I feel that you simply forget to implement some of them. In my case it's relevant to hook now the values "BootLoader" and "RadioVersion" because I need to change them.

For the "RadioVersion" in API <14 you need to hook member RADIO of class Android.os.Build; and with API >= 14 hook the function Android.os.Build.getRadioVersion().
See https://developer.android.com/reference/android/os/Build.html

For the "BootLoader" it's more easy: the BOOTLOADER member of Android.os.Build (like you do for "Brand" for example).

I hope you can complete the list.
Regards!

**Comment by lars18th** [comment]
Hi @bigsinger ,

The "Hardcoded" value of the "BootLoader" is empty. Please, set it! If you don't know in your Meizu device, then use "oem-bootloader" for example.

Regards.

**Comment by lars18th** [comment]
Hi @bigsinger ,

Please, can you upgrade to v.1.17 incorporating RADIO and BOOTLOADER hooks?

Thank you!

**Comment by bigsinger** [comment]
DONE

**Comment by lars18th** [comment]
Hi @bigsinger ,

Tested with v1.18, and it works. Thank you!

So, now the list of pending hook values is:

- googlead_id
- IP
- NetType
- NetworkOperatorName
- Resolution
- Width
- SimSerialNo
- Height

Futhermore, I request to add also this other value: "SKU". It gets from the system property "getprop ro.boot.hardware.sku". For hook it, you can use this example:
http://forum.xda-developers.com/showpost.php?p=69786196&postcount=3

I feel you can use the same way for hooking other "system prop" values, like "Density" (getprop ro.sf.lcd_density).

I hope you can complete the list in a future release.
Regards!

**Comment by lars18th** [comment]
Hi,

We continue in #31 . So I close this issue.

I suggest to also close another already fixed issues (please, review Chinese theads).
