### ISSUE TITLE
Where to download last releases

### ISSUE THREAD

**Issue by lars18th** [bigsinger/AndroidIdChanger#13]
Hi,

It seems that the version v1.7 is out. However, in the releases directory the last listed version is v1.4:
http://github.com/bigsinger/AndroidIdChanger/tree/master/release

Where we can download the recent versions?

**Comment by bigsinger** [comment]
you can download any version, it will show you a dialog on start to  let you to update to the lastest version.

**Comment by lars18th** [comment]
> you can download any version, it will show you a dialog on start to let you to update to the lastest version.

Thank you!
I suggest to put also this info in the README homepage.

**Comment by lars18th** [comment]
Hi,

I see my fault: The opening window message (alert of update) is in Chinese. So I don't noted that I can upgrade.

Plaase, can you translate this message to English too?
Futhermore, can also put the most recent versions in the repository?

Thank you!

**Comment by bigsinger** [comment]
I used a SDK for upgrading, cause the SDK is Chinese, it has a upgrade template which wrriten in Chinese, I can not translate the template but only the content.

**Comment by lars18th** [comment]
> I used a SDK for upgrading, cause the SDK is Chinese, 
> it has a upgrade template which wrriten in Chinese, 
> I can not translate the template but only the content.
OK.

So, then I suggest to include in the "Settings" activity one option for launch the "update".

**Comment by bigsinger** [comment]
it's a good idea!!!

**Comment by lars18th** [comment]
Hi,

As this it's already implemented, and the module is also in the public Xposed's repo... then I close it.
