### ISSUE TITLE
UI: Original attributes

### ISSUE THREAD

**Issue by lars18th** [bigsinger/AndroidIdChanger#16]
Hi,

I like leave some of the values as original. So I suggest these improvements:

- In section "AFTER" write in gray color the attributes not changed.
- In section "BEFORE" a toggle button for "reset" (or copy) the original value.
- Use any "empty" value as "original" one.

I hope you agree to implement this.
Regards.

**Comment by bigsinger** [comment]
Great advice! I'll implement this next version.

**Comment by lars18th** [comment]
Hi,

Regarding the current UI for the hooked values, I suggest another improvement:

- With the current interface all values are saved in then "phoneinfo.xml" file. Even if values aren't changed. And when you don't modify the value the hook needs to be disabled. So, for non-hooked values the correct values inside the "phoneinfo.xml" file is "" (null).

Therefore I suggest to add at the left of each value in the "After" section a toogle (check box, like "[ ]" and "[X]") to enable/disable the value. So, when the value isn't checked the saved preference is "" (null).

You agree?

**Comment by lars18th** [comment]
Hi @bigsinger ,

I hope you soon implement this. At time, I need to manually edit the file "phoneinfo.xml".

Regards.

**Comment by lars18th** [comment]
Hi,

This is in v.1.13 too. Great!

However, I see a problem: when changing the values: sometimes the values are lost in the UI (some of them). Then the values in the "phoneinfo.xml" are lost. So, it's a pain to re-edit the values manually (I do with nano in the the shell).

Perhaps, will be better to save the value all the time in the XML file and save too a boolean for enable/disable.
What you think?

**Comment by lars18th** [comment]
Hi,

Sorry! I see now the boolean value in the "CHANGER.xml". So, this is completed.

I only need to comment, that when editing the values, sometimes they are lost. Perhaps it's a problem when upgrading from v1.12 to v.1.13.

So I close it.
Thank you!
