### ISSUE TITLE
UI: New format for "Specific App" Activity

### ISSUE THREAD

**Issue by lars18th** [bigsinger/AndroidIdChanger#17]
Hi,

I suggest a new format for the UI Activity "Specific App".
Here an example:

```
≡  Changer v1.x
--------------------
 System wide  (-x)

Application 1   [ ]
Application 2   [ ]
Application 3   [X]
Application 4   [ ]
Application 5   [ ]
      ...
```

The idea is integrate a global switch for selecting "global wide" chaging. This switch enables the rewrite of values for the entire system when it's on. Futhermore, when it's on then the list of Apps is grayed (disabled). However, when the switch is off, then you can select the Apps you like to rewrite. You can select one or more; and only in these Apps the values are changed.

You agree with this _new_ format?

**Comment by bigsinger** [comment]
3qs, i agree with this, show me the code please

**Comment by lars18th** [comment]
Hi @bigsinger ,

More or less is the code of the activity MagiskHide. See here:
https://forums.oneplus.net/attachments/1499363262961-jpg.553607/

And the code is here :
https://github.com/topjohnwu/MagiskManager/tree/master/app/src/main/res/layout

I hope this helps you!

**Comment by bigsinger** [comment]
@lars18th :+1:

**Comment by bigsinger** [comment]
@lars18th i down the MagiskManager project, but i can not compile it, the errors:
>Gradle 'MagiskManager-master' project refresh failed
Error:A problem occurred configuring project ':app'.

we can not connect google in China, maybe it's the reason.

if you find some simple demo source about magisk, please show me

**Comment by lars18th** [comment]
> if you find some simple demo source about magisk, please show me

In the meantime, you can do these two simple changes if you agree:

1) Order by name the list of Apps (now it's quite complex to found one program in the current list).
2) Add a simple checkbox for enable/disable system wide changes.

> we can not connect google in China, maybe it's the reason.

I'll try to help you!

**Comment by lars18th** [comment]
-

**Comment by bigsinger** [comment]
you metioned the "system wide" several times, does it mean Global(or entire system which i mod in one app will affect  other apps)?

**Comment by bigsinger** [comment]
> Add a simple checkbox for enable/disable system wide changes.

which values are systemwide? can you list?

**Comment by lars18th** [comment]
> you metioned the "system wide" several times, does it mean Global
> (or entire system which i mod in one app will affect other apps)?

Yes!

> which values are systemwide? can you list?

System wide = All changed values are for **all** Apps (including Android UI).
Per App = Changed values are **only** for selected Apps (all others use the stock values).

So, it's one or other... can't be both! ;-)

**Comment by lars18th** [comment]
Hi,

This is not directly related to this issue, but I post here because has some relation.
Please, change the order of the "Setting" activity. I suggest to put in this order:

```
Settings:
 Enable Debug Mode     [O-]
 Use Hardcoded Values  [O-]

Advanced:
 To address:
 Sender Mail:
 Sender Mail Server Pass:
   <Send Device Info to Email>
```

You agree?

**Comment by bigsinger** [comment]
agree

**Comment by YasirNasutionAH** [comment]
Please help me, I'm just new at here and the app.

When I started the app and choose random to changer my ID phone and other, it mention like "changer already save! But no specific app. *******"

Please help me, how can I fix it.

I'm just a newbie about this kinda, but really I need some help.

Please teach me how to do.

**Comment by bigsinger** [comment]
@lars18th any idea?

**Comment by bigsinger** [comment]
@YasirNasutionAH in setting section

**Comment by YasirNasutionAH** [comment]
Advanced:
 To address:
 Sender Mail:
 Sender Mail Server Pass:
   <Send Device Info to Email>

How/what shall I put to those options

What/who's email and passwords

**Comment by YasirNasutionAH** [comment]
@bigsinger my phone setting or the app setting?

**Comment by bigsinger** [comment]
1、your email and passwords
2、app setting

**Comment by lars18th** [comment]
Hi @YasirNasutionAH ,

> When I started the app and choose random to changer my ID phone and other, 
> it mention like "changer already save! But no specific app. *******"

After save the values that you like to change, you need to open the left menu, open "Specific App" and select the Apps that you like to hook (only selected Apps will see the random ID phone value). And *after* remember to reboot!

**Comment by lars18th** [comment]
Hi @YasirNasutionAH ,

> To address:
> Sender Mail:
> Sender Mail Server Pass:

For regular use you don't need to complete these options!

**Comment by lars18th** [comment]
Hi @bigsinger ,

In version v1.15, when upgrading, the list of Apps is cleared. This is intentional?
Futhermore, all values in the replace list are selected. I need to unselect to recreate the list and "save".

You changed something in the source related to the preferences?

**Comment by bigsinger** [comment]
cause TAG is CHANGER, i changed as CHID
i'll restore it as CHANGER

**Comment by lars18th** [comment]
> cause TAG is CHANGER, i changed as CHID
> i'll restore it as CHANGER

I see some change in the "shared_prefs" directory. I hope you can fix all the current bugs!

**Comment by lars18th** [comment]
Hi @bigsinger ,

Two suggestions for the next version (if you agree):

- Remove the "Changer" App from the list. Enabling it can produce indeterminated results!
- When selecting the option, the "waiting" message (when loading the list) is printed only in Chinese. Translate it to English, please.

Regards.

**Comment by bigsinger** [comment]
1.  can not enable "Changer" App from the list, you can try it , it ' ll show a toast.
2. ok

**Comment by lars18th** [comment]
Hi @bigsinger ,

OK. All is correct in v1.20. Thank you!
So I close this issue.
