### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by lars18th** [bigsinger/AndroidIdChanger#18]
Hi,

Even you can't post the full source code of the project, I suggest to share the main java file (the one with hooks). This will simplifies the review of the code and creates the oportunity for sharing ideas.

You agree?

_(Note: Simply put "HookerPhone.java" in "/src" subdirectory)._

**Comment by bigsinger** [comment]
uploaded

i'v not fix all you suggested, if u have time, just fix and push .

**Comment by bigsinger** [comment]
added u as Collaborators

**Comment by lars18th** [comment]
Hi @bigsinger ,

> uploaded

Great! Only, please remember to update this file when you upload a new release.
Thank you!

> i'v not fix all you suggested, if u have time, just fix and push .

Don't worry!

> added u as Collaborators

I'm glad to collaborate!
However, I prefer that you continue with the coding. I'll assist with testing, ideas and helping.

**Comment by bigsinger** [comment]
> However, I prefer that you continue with the coding. I'll assist with testing, ideas and helping.
>  remember to update this file when you upload a new release.

of course, i'll do this in my spare time.

**Comment by lars18th** [comment]
OK! Only remember to upload "/src/HookerPhone.java" for each new release, please!
