### ISSUE TITLE
[Off topic]: Nexus 9 with Android Nougat

### ISSUE THREAD

**Issue by lars18th** [bigsinger/AndroidIdChanger#20]
Hi @bigsinger ,

Which ROM of Android you use in your Nexus 9?

I'm searching for one 7.0 version (SDK 24) compatible with Xposed. You know about DU (Dirty Unicorns)?

**Comment by bigsinger** [comment]
3.10.101-g5afd1b7
android-build@vpeb1.mtv.corp.google.com #1 
Wed Jun 29 17:18:50 UTC 2016

NRD90M

**Comment by lars18th** [comment]
So, you use a STOCK ROM.
You accept to install a Custom ROM? The idea is quite simple: with a custom ROM it's more easy to root and intstall Xposed.

**Comment by lars18th** [comment]
Hi,

For SDK 25 (Android 7.1) you can try Slim ROM:
https://slimroms.org/#/device/flounder

Remember to install TWRP:
https://twrp.me/htc/htcnexus9.html

I hope you can test it!

**Comment by bigsinger** [comment]
it's friend’s device, i can't rom it

**Comment by lars18th** [comment]
OK. I'll continue searching for a solution.
Which recovery is installed on this device? It's already rooted? With which method?

**Comment by lars18th** [comment]
Hi @bigsinger ,

It's now running this module in your Nexus 9 with Nougat?
I hope so!
