### ISSUE TITLE
Core/UI: Share values over EMAIL

### ISSUE THREAD

**Issue by lars18th** [bigsinger/AndroidIdChanger#22]
Hi,

I suggest to include a method for sharing by email (for make a backup or send to developer) the used values.
You can use this code for use your regular email client installed in your device:

```
public void composeEmail(String[] addresses, String subject) {
    Intent intent = new Intent(Intent.ACTION_SENDTO);
    intent.setData(Uri.parse("mailto:")); // only email apps should handle this
    intent.putExtra(Intent.EXTRA_EMAIL, addresses);
    intent.putExtra(Intent.EXTRA_SUBJECT, subject);
    if (intent.resolveActivity(getPackageManager()) != null) {
        startActivity(intent);
    }
}
```

You agree?

**Comment by bigsinger** [comment]
i know that, considering the device is public using by many people, no one will config his email on the device, so, when i share, i should type my email addr an pswd.  and my email will be saw by someone else.

**Comment by lars18th** [comment]
Hi,

Alternatives:

1. Public EMAIL service: I don't know about that, as SPAM is blocked in almot all networks.
2. Enable "Share" service: This will provide the option for use other Apps (despite E-Mail) for "sending" the content. However, with a "shared" device this can be also a problem.
3. Use a free "post" service, like Pastebin.com.

Try what you prefer!

**Comment by bigsinger** [comment]
maybe i can use a debug version with email function myself, the release version without this funtion.

**Comment by lars18th** [comment]
Hi,

> maybe i can use a debug version with email function myself, the release version without this funtion.

Well, you can implement the option 2, and inside a "debug" version add too a hardcoded e-mail function.

You agree?

**Comment by bigsinger** [comment]
Let me see

**Comment by lars18th** [comment]
Hi @bigsinger ,

I feel it will be also interesting to use this tool for getting system propertities from any device.
So, I suggest to incorporate a PRINT or SHARE of "text" (not XML) values, even when the device isn't rooted or the Xposed framework is running. The objective is use it for getting the values of other devices. Then when can use the values for impersonate these devices.

You agree?

**Comment by bigsinger** [comment]
1 but how to disign the UI ? any idea?
2 i output the device info as a  html table that can easyly read. 

may i output the device info to a file in the path '/data/local/tmp'? maybe  we can pull it to pc even on the unrooted device .

**Comment by lars18th** [comment]
> 1 but how to disign the UI ? any idea?

Anything simple. For example a simple entry in the hamburger menu called "export data". And when you select it, you see the list of the HTML and you can save in a file or share using another tool.

> 2 i output the device info as a html table that can easyly read.

I agree! Great idea!

**Comment by lars18th** [comment]
Hi @bigsinger ,

As the new "mydevice.htm" file is supported in v1.19... I suggest to change the E-Mail Sharing with "Sharing file". See here:
https://developer.android.com/training/secure-file-sharing/setup-sharing.html

The idea is this: use the Android's share function for share this file with any App.
What you think?

**Comment by bigsinger** [comment]
:+1:

**Comment by lars18th** [comment]
Hi @bigsinger ,

Great upgrade in v1.20! Saving the file "mydevice.htm" in the SDCard it's working.
I'll help you with the "sharing" issue (I comment it in #1).

However, please try to also generate the "hookdevice.htm". And export both files in the next version.
You agree?

Note: Perhaps you need to rethink in remove the "Advance" section in "Settings" (as a comment, change from "Setting" to "Settings" in the menu name!).
