### ISSUE TITLE
Xposed Module Repository

### ISSUE THREAD

**Issue by lars18th** [bigsinger/AndroidIdChanger#23]
Hi,

Great to publish this module in "repo.xposed.info". However, I suggest to enhance the description. For example: indicate the supported Android versions (at time, only [KK,L,M]).

Thank you for this!

**Comment by bigsinger** [comment]
updated:

Support: Android 4.x ~ 6.x

**Comment by lars18th** [comment]
Great!

For "open Betas" you can also upload versions with different "Release type". Perhaps you like to use it!

And, please upgrade the description here as it isn't in sync with the README! For example, for the "Per App" function.

Regards.

**Comment by bigsinger** [comment]
can you write for me?

**Comment by lars18th** [comment]
> can you write for me?

If you have troubles with the access to it, then of course!
However, this can be a simple option: create a README.repo file (text format). We can update this file here and when you publish a new version in the public repo then you will update the file.

You agree?

**Comment by bigsinger** [comment]
i added a README.repo file on github, you can write somthing first

**Comment by lars18th** [comment]
> i added a README.repo file on github, you can write somthing first

Thank you! I'll do when the next (1.13) version comes! :smile:

**Comment by lars18th** [comment]
HI @bigsinger ,

I suggest to upload the version v1.13 to the oficial repository.
This this on "README.pro" if you like:

-------------------
AndroidIdChanger
English:
•	View and Change the value of IMEI, Android Id, Serial Number, Wifi Mac Address and service set identifier (SSID) of the current wifi network, Google advertising id, Bluetooth mac address, and so on.
•	You can random or manual set these values.
•	Can apply the values System Wide or in Per APP basis.
•	Note for Nougat support: You need to grant privileges to the preferences file. We’re working on fix it. In the meantime execute this command one time from an ADB shell with su/root privileges: "chmod 664 /data/data/com.bigsing.changer/shared_prefs/phoneinfo.xml"
How to use :
•	Install app.
•	Enable module in xposed framework.
•	Open app and enter new values.
•	Reboot.
中文 (Chinese):
•	查看并修改安卓手机设备信息： IMEI、AndroidID、Wifi Mac、SerialNum、Wifi SSID、手机号、Bluetooth Mac、Google Ad Id、Wifi BSSID、IMSI、Sim卡状态、运营商信息、机器型号、制造商、品牌、系统版本、CPU_ABI、CPU_ABI2、SDK、BuildID、分辨率、IP等。
使用方法：
•	安装APP，运行APP即可查看手机信息，可以随机修改信息
•	安装Xposed
•	在Xposed框架中启用本模块
•	重启手机

-------------------

**Comment by bigsinger** [comment]
why not update the README.repo file directly? u r Collaborator
