### ISSUE TITLE
DEBUG: Improve logs

### ISSUE THREAD

**Issue by lars18th** [bigsinger/AndroidIdChanger#25]
Hi,

In the lasted vesion (v1.12) in the logs isn't writed the hooked values. Without this it's impossible to debug which value is used.

I suggest to change to something like this:

```
        //////////////////////////////////////////////////////////////////////////
        // FINGERPRINT
        if (Constant.HARDCODED) {
            modValue = "Meizu/meizu_mx3/mx3:4.4.4/KTU84P/m35x.Flyme_OS_3.7.3.20140909113158:user/release-keys";
        } else {
            modValue = PhoneInfoUtils.getValue("FingerPrint");
        }
        if (TextUtils.isEmpty(modValue)) {
            XposedLog.logd("HookerPhone.hook(): no hook FINGERPRINT, it's  null");
        } else {
            final String hookValue = modValue;
            try {
                XposedHelpers.setStaticObjectField(Build.class, "FINGERPRINT", hookValue);
                XposedLog.logd("HookerPhone.hook(): hooked FINGERPRINT with " + hookValue);
            } catch (Exception e) {
                XposedLog.logd("HookerPhone.hook() : error hooking FINGERPRINT");
            }
        }
        //////////////////////////////////////////////////////////////////////////

```

This will be usefull too when multiple calls are done (like with IMEI) and some exception is triggered. With this will be more easy to find which call fails.

You agree?

**Comment by lars18th** [comment]
Hi,

After apply the solution described in #26 I started to use this module in "real world".
Now I have two problems:

1. As the module doesn't print the hooked values (as described above) I can't be 100% sure that the correct hooked values are used.

2. When the module is running it generates at time a lot of debug. I suggest to add a "Settings" parameter (like for hardcoded values) for enable/disable LOG. In any case, the "errors" (like for example, when a exception is cached) needs to be logged even when the log is disabled.

You agree?

**Comment by lars18th** [comment]
Hi @bigsinger ,

At time my Xposed's LOG is increasing a lot (after a half day the size is around 0,5MB). Please, can you add the option for enable/disable LOGs? I like to use it without logs in the daily use, and enable it only when debugging.

Futhermore, I see all the time this in my log:

```
10-23 16:19:47.517 I/Xposed  ( 2948): CHANGER: HookerPhone.hook(): no hook FINGERPRINT, it's  null
```

But my FIGERPRINT value is modified in the "phoneinfo.xml" file. So, please, add also the option for LOG the hooked values. I need to check what values are hooked, and which aren't.

Thank you very much for this invaluable module!

**Comment by lars18th** [comment]
Hi @bigsinger ,

Here an elegant code solution from enable/disable logs:

```
    private static void logDebug(String msg) {
        if (BuildConfig.DEBUG) Log.d(X_SUDOHIDE_TAG, msg);
    }
```

Please, implement it in the next version, and not forge to add the "XposedLog.logd("HookerPhone.hook(): hooked VALUE with " + hookValue);"

Regards! :smile:

**Comment by lars18th** [comment]
Hi @bigsinger ,

Even before revolve the issue #26, please can you incorporate this suggestion (with also #16)?
It's a pain to use the module with a lot of log lines! The option for disable/enable the log is a must have.
Futhermore, the option for printing in logs the hooked values is valuable.

Thank you!

**Comment by lars18th** [comment]
Hi @bigsinger ,

This is already implemented in v1.13. Congratulations!

However, before closing this issue I have one suggestion: Please, print the FIRST and LAST debug lines even when the log is disabled. Why? Because this serves as an indication that the module is active and working.

I speak about something like this when debug is disabled:

```
10-30 09:23:30.027 I/Xposed  ( 2947): CHANGER: HookerPhone.hook() begin  >>>>>
10-30 09:23:37.055 I/Xposed  ( 2948): CHANGER: HookerPhone.hook() end    <<<<<
```

I hope you agree for the next release.

**Comment by lars18th** [comment]
Hi @bigsinger ,

I suggest to also print the line of hooked Apps when no log is enabled. So the minimal log will be three lines only: BEGIN, LIST OF APPS, and END. 

This is the best (in my opinion) for the regular run of the module.
You agree?

PD: Don't forget for printing relevant errors when the log is disabled al well!

**Comment by lars18th** [comment]
Hi @bigsinger ,

In the version v.1.14 I see changes in the LOG format. Good job!

However, the current format is inconsistent: some times the line begins with "[CHANGER]:" but sometimes not. Futhermore, the "start" and "end" section use different text. When the log is disabled, I see two lines (each time an App is started) with "[handleLoadPackage]" and "hookPakages: ". This is quite confusing!

So I suggest to use **all the times** the same prefix. Futhermore, I suggest a short value, like "[CHID] " (from CHangeID).

You agree?
The idea is simple: All lines printed by your App start with the same "[CHID] " text.

**Comment by bigsinger** [comment]
DONE

**Comment by lars18th** [comment]
Hi @bigsinger ,

Sorry! I installed v.1.15 using the upgrade method, and the LOG now doesn't work!
Even with "debug" enabled or disabled I can't see any message from ChangeID.
Please, can you fix it?

Thank you!

Note: Remember to upgrade (if you can) the source file!

**Comment by bigsinger** [comment]
i test it, it works .

**Comment by lars18th** [comment]
> i test it, it works .

It doesn't work in my phone and I don't know why!

**Comment by lars18th** [comment]
Hi @bigsinger ,

In the updated src code I see three different log functions...

```
XposedLog.log("hook begin"); 

XposedLog.logd("no hook IMEI, it's  null");

XposedLog.loge("error hooking PhoneNumber");

XposedLog.log("hook end\n");
```

Please, check that **all** of them include the pre-print "[CHID] ". And I suggest too that the "begin"/"end" add a more visible text, like "HookerPhone.hook() begin  >>>>>" and "HookerPhone.hook() end    <<<<<".

I hope you agree! :smile:

**Comment by lars18th** [comment]
Hi @bigsinger ,

Updated to v1.16. And I continue witout seeing the logs.
Any idea why?

**Comment by bigsinger** [comment]
not work on android N ?

**Comment by lars18th** [comment]
> not work on android N ?

The hook works. But the LOG doesn't. I need to investigate more.

**Comment by lars18th** [comment]
> The hook works. But the LOG doesn't. I need to investigate more.

After more investigation, I can only conclude that something is wrong. In last versions (v.1.16 & 1.15) the log from this module isn't printed in the Xposed LOG. Please, review the changes from v1.14 to v1.15 for see where is the problem.

I hope you can fix it.

**Comment by bigsinger** [comment]
i rename the TAG as CHANGER

**Comment by bigsinger** [comment]
@lars18th 

public static void hook(XC_LoadPackage.LoadPackageParam param) {
        XposedLog.log("hook begin");    //绝对输出
...

XposedLog.log("hook end\n");  //绝对输出
}

    public static void log(String msg) {
        Log.i(Constant.TAG, msg);
        //XposedBridge.log(msg);
    }

**Comment by lars18th** [comment]
Hi @bigsinger ,

Why you commented "//XposedBridge.log()" function?
Please update the source file and add the logging functions to this file, if you can.

I'll check v1.17.

**Comment by bigsinger** [comment]
Log.i(Constant.TAG, msg);  also can log...

**Comment by lars18th** [comment]
So, then check that "XposedLog.log()" calls to "log(String msg)".
Perhaps you're overloading a member, and using incorrect call.

**Comment by lars18th** [comment]
Hi @bigsinger ,

In versions v.1.18 I continue without LOGs!
You see the logs in your device? Please, share your current config (Xposed versions, rooting method, etc.). We need to know why the LOGs doesn't work in some devices!

Regards.

**Comment by bigsinger** [comment]
yes. the tag is CHANGER, not CHID, not xposed

**Comment by lars18th** [comment]
> yes. ... not xposed

Now I see it! you changed from Xposed LOGs to Android System Logs. So, this is the change!

However, why this change? The Xposed Log is great. More easy to see and productive.

**Comment by bigsinger** [comment]
The difference is the tag（xposed or CHANGER）, i want to Distinguish my module's log with other module

**Comment by lars18th** [comment]
> The difference is the tag（xposed or CHANGER）, i want to Distinguish my module's log with other module

Yes, and this is a good idea! However, at time, your log isn't writed in the Xposed log.
For distinguishing inside the Xposed log from other modules, you only need to "pre-prend" one text. For example: "[CHID] ". This is the way done by some great modules (for example, by GrabityBox... it uses "[GB] "). So any log entry inside the Xposed log that starts with "[CHID] " will be from you module.

The change it's quite easy: You restore to use "xposed" as the "tag" and you pass to the "xposed.log()" function then "Str" parameter plus your _tag_, like this **xposed.log("[CHID] " + Str)**.

You agree?

**Comment by bigsinger** [comment]
the implemention of method 'XposedBridge.log' is: 
	public synchronized static void log(String text) {
		Log.i(TAG, text);
	}

it also uses the android's log function: Log.i
the diffrence is the TAG is hardcoded as Xposed.

**Comment by lars18th** [comment]
Hi @bigsinger ,

Yes, and you can to use this code for example:

```
public static void log(String msg) {
    XposedBridge.log( "[CHID] " + msg);
}
```

or use the same code as GrabityBox:
http://github.com/GravityBox/GravityBox/blob/985eb076994b3600b5beaea79d19a1c3f6ed1bcf/src/com/ceco/nougat/gravitybox/PermissionGranter.java#L33

Regards! :smile:

**Comment by lars18th** [comment]
Hi @bigsinger ,

You will implement my suggestion in the next v.1.19 ?
:smile:

**Comment by bigsinger** [comment]
u win!

**Comment by lars18th** [comment]
Great! :smile:

**Comment by lars18th** [comment]
Hi @bigsinger ,

I see now LOGs in Xposed with the version v1.19. Thank you!

However, some troubles. See this part of the LOG:

```
11-14 13:41:17.280 I/Xposed  ( 5140): CHANGER: App Hook List: flar2.devcheck
11-14 13:42:22.103 I/Xposed  ( 5305): CHANGER: App Hook List: flar2.devcheck
11-14 13:42:22.120 I/Xposed  ( 5305): CHANGER: hook begin
11-14 13:42:22.160 E/Xposed  ( 5305): CHANGER: error hooking Build.TIME
11-14 13:42:22.164 E/Xposed  ( 5305): CHANGER: error hooking TIME
11-14 13:42:22.174 I/Xposed  ( 5305): CHANGER: hook end
```

- The setting option "Debug Mode" has no function. I see all the time the same prints, even if it's enabled or disabled. Please, check the code!

- In Android 7.0 I see these two errors in hooking: TIME & Build.TIME. Please, can you verify the code?

Now another suggestions regarding the LOGs:

I see a lot of lines with the "CHANGER: App Hook List: flar2.devcheck". I suggest to print this **only** with the "Debug Mode" enabled. And leave only "hook begin" and "hook end" to print all the time.
Futhermore, I suggest a modification for this two lines. Example:

```
11-14 13:42:22.120 I/Xposed  ( 5305): CHANGER: hooking package [flar2.devcheck] BEGIN
11-14 13:42:22.174 I/Xposed  ( 5305): CHANGER: hooking package [flar2.devcheck] END
```

The idea is add the name of the package that is hooked and print the begin/end in uppercase.
You agree?

**Comment by bigsinger** [comment]
done

**Comment by lars18th** [comment]
Hi @bigsinger ,

Thank you for incorporating the name of the hooked packaged in the log.

However, I continue with troubles with logs. Please, review the source regarding these issues:

1. The hooked values are never printed. Even when the "Debug mode" is enabled in Preferences (I have this in "CHANGER.xml": < boolean name="debug_mode" value="true" / >).

2. Even if I don't have the System Wide Hook (In "CHANGER.xml": < boolean name="hook_all_app" value="false" / >) I see this message in the LOG:
`
11-15 09:11:21.015 I/Xposed  ( 2172): CHANGER: All App(PackageName Without [android.])Hooked, You Can Turn Off On [Settings] And Add App By [Specific App].
`
I feel it's an error in your code, as only the packages listed are in fact hooked.

3. Messages about "CHANGER: All App" & "CHANGER: App Hook List:" are printed multiple times. I know the code runs each time a package is loaded. However, I suggest to use a global boolean var for checking it's FirstTimeRun, and execute the PrintLog only one time. You agree?

I hope you can improve it in the next release.
Regards.

**Comment by bigsinger** [comment]
please check the attr of "CHANGER.xml" ,maybe no access in other app

**Comment by lars18th** [comment]
> please check the attr of "CHANGER.xml" ,maybe no access in other app

```
android:/data/data/com.bigsing.changer/shared_prefs # ls -lZ
total 48
-rw-rw-r-- 1 u0_a279 u0_a279 u:object_r:app_data_file:s0:c512,c768 1281 2017-11-15 10:10 CHANGER.xml
-rw-rw---- 1 u0_a279 u0_a279 u:object_r:app_data_file:s0:c512,c768  156 2017-11-15 10:07 ThemeColor.xml
-rw-rw---- 1 u0_a279 u0_a279 u:object_r:app_data_file:s0:c512,c768  118 2017-11-15 10:07 com.bigsing.changer.BETA_VALUES.xml
-rw-rw---- 1 u0_a279 u0_a279 u:object_r:app_data_file:s0:c512,c768  192 2017-11-15 10:07 crashrecord.xml
-rw-rw---- 1 u0_a279 u0_a279 u:object_r:app_data_file:s0:c512,c768 2309 2017-11-15 10:07 phone.xml
-rw-rw-r-- 1 u0_a279 u0_a279 u:object_r:app_data_file:s0:c512,c768 2330 2017-11-15 10:10 phoneinfo.xml
android:/data/data/com.bigsing.changer/shared_prefs #
```

This isn't the problem!

**Comment by lars18th** [comment]
Hi @bigsinger ,

Some suggestions:

- Make as default values (if you can't load the preferences) as this:
-- System Wide Hook: 'false'  (you don't like to hook anything if you can't read preferences)
-- List of Hook Apps: 'null'  (empty list)
-- Debug: 'true'  (if you can't load the preferences, then log all)
-- Use Hardcoded Hook values: 'false'  (not change anything)
- If you can't read the preferences, then print a log error (use a try block for read them).
- Use the global "FirstTimeRun" var for printing only some messages one time (the messages of hook BEGIN and END I feel need to be printed all the times).

I feel this can simply the check of errors.
you agree?

**Comment by bigsinger** [comment]
Considering new users, they want to see the effect of my app, if  hook does'nt work, they uninstall it.
so i set hook_all_app default as true

**Comment by lars18th** [comment]
> Considering new users, they want to see the effect of my app, if hook does'nt work, they uninstall it.
so i set hook_all_app default as true

As default in the UI and preferences... yes! I don't comment this. You're right!

My suggestion is for "values when you can't read the preferences". That is, the part of the code executed when Xposed calls the Hook. In this point you read the preferences. And my suggestion is put this in a try block. And if the try fails or you get 'null' values, then use my suggested values... as these values will help to debug and find the problem (as it's my case now).

you agree?

**Comment by bigsinger** [comment]
:+1:

**Comment by lars18th** [comment]
Hi @bigsinger ,

When you implement the try block for reading the preferences and the FirstTimeRun, please do it in this sense (if you agree):

```
FirstTimeRun = true; SystemWideHook = false; HookApps: ""; Debug = true; HardcodedHookvalues = false;
If (FirstTimeRun) then {
   LOG("[CHANGER]: Starting");
   try {
      ReadPreferences();
   } Catch(e) {
      LOG("[CHANGER]: Can't read preferences! Using defaults.");
   }
   LOG("[CHANGER]: ...");  // Print here basic preferences values.
   FirstTimeRun = false;
}
...
```
Please note that LOG prints only if "Debug == true".
And for other re-entrant messages, use "FirstTimeRun == true" for know if you need to re-print the log.

This it's only an idea. :smile:

**Comment by lars18th** [comment]
Hi @bigsinger ,

You agree to implement the last suggestion? This will help me to support you in fixing/detecting current bugs. Remember that the current version has troubles with LOGs in Nougat.

Regards!

**Comment by lars18th** [comment]
Hi @bigsinger ,

With the version v1.21 only _minor_ bugs persists. This version is great, so I suggest you upload it to the official Xposed Repository. From this version all users can use this module reliable!

However, this point regarding the LOGs it's very annonying... See my log now:

```
11-28 09:08:02.382 I/Xposed  ( 2168): CHANGER: All App(PackageName Without [android.])Hooked, You Can Turn Off On [Settings] And Add App By [Specific App].
11-28 09:08:02.382 I/Xposed  ( 2168): CHANGER: hooking package [com.qualcomm.atfwd] BEGIN
11-28 09:08:02.433 I/Xposed  ( 2168): CHANGER: hooking package [com.qualcomm.atfwd] END
```

And I don't see anything related to hooks, only lines like "CHANGER: hooking package [...] BEGIN / END" . However, in my "CHANGER.xml" I have this:

```
  <boolean name="hook_all_app" value="false" /> 
  <string name="packages">flar2.devcheck </string> 
  <boolean name="use_hardcoded_value" value="false" /> 
  <boolean name="debug_mode" value="true" /> 
```

And in fact only the package "flar2.devcheck" is hooked, and only the values that I have correctly incorporated in "phoneinfo.xml". So, I feel something is wrong in some part of the code. Please, can you try to implement my suggestion of "safe loading of preferences" pointed at
https://github.com/bigsinger/AndroidIdChanger/issues/25#issuecomment-344627090

The idea is this: if the preferences can't be loaded, then use a default safe group. This can be "SystemWideHook = false; HookApps: ""; Debug = true; HardcodedHookvalues = false;". Please, don't confuse this with "default" values in the App (that are right, now). This are the values when you "can't load the preferences". In this scenario you like to: 1) No hook anything (SystemWideHook = false; HookApps: ""; HardcodedHookvalues = false;) and 2) You like to DEBUG all (Debug = true;).

So, please can you try it? I hope with this change we can isolate where is the trouble.
You agree? :smile:
