### ISSUE TITLE
能不能加上一个语言伪装？

### ISSUE THREAD

**Issue by lukemin** [bigsinger/AndroidIdChanger#28]
能不能加上一个语言伪装？很多中文app非中文语言没有广告

**Comment by bigsinger** [comment]
告诉我方法

**Comment by lukemin** [comment]
app local的功能啊 appsetting是 也有 选择语言

**Comment by bigsinger** [comment]
@lars18th any idea?

**Comment by lars18th** [comment]
Hi,

**I don't read Chinese.** However, I suspect you search for a method for changing the used language in an App.
If it this true, then I suggest to use another Xposed module: App Settings (original from Rovo, the developer of the Xposed Framework). Some forks exists for Nougat, for example
https://forum.xda-developers.com/xposed/modules/locale-appsettings-nougat-t3641860

I hope this helps!

**Comment by lukemin** [comment]
hi，I know the modified appsettings for nougat and I am using it now. I am also using your app now. I wanna you add this function to your app, then I can uninstall that one.

**Comment by lukemin** [comment]
appsettings for nougat only has local function work. Other funcions do not work at all

**Comment by lars18th** [comment]
Hi @lukemin ,

> I wanna you add this function to your app,
> appsettings for nougat only has local function work

Please, show where is the code for the hooking of the language locale in the AppSettings and we'll try to include it.

**Comment by lukemin** [comment]
settings ====》local   please see pic below


![20171116110521](https://user-images.githubusercontent.com/12003375/32871891-a369fcce-cabe-11e7-8ec9-736e0ffb9729.png)

**Comment by lars18th** [comment]
Hi @lukemin ,

I see the value in the UI of the APP. The request is about the "source code" of the hook.

Futhermore, I review the source code from
https://forum.xda-developers.com/xposed/modules/locale-appsettings-nougat-t3641860
and hooking the LOCALE is quite complex. Sorry, I don't know how to integrate it!

I suggest to use both modules at time. No other way to achieve your objective. Sorry!
