### ISSUE TITLE
使用过程中相关BUG及建议

### ISSUE THREAD

**Issue by studio888** [bigsinger/AndroidIdChanger#3]
1.xposed中模块已启用并重启,可总提示未启用,实测改变生效
2.作者能否不要进行全局HOOK, 建议可设置对单个APP进行HOOK
3.建议增加保存配置及加载配置的功能,有些HOOK并非一次性
以上仅个人建言, 谢谢.

**Comment by bigsinger** [comment]
可以试试1.7版本

**Comment by lars18th** [comment]
I suggest to add to the TODO issue #31 the option for a global hooking (now difficult to achieve, pending for implementing in the future).
Then close this issue.

Regards.

**Comment by bigsinger** [comment]
when no app is added to the hook list, i'll hook all app which packagename not contain 'android'

**Comment by lars18th** [comment]
Hi @bigsinger ,

> when no app is added to the hook list, i'll hook all app which packagename not contain 'android'

Ah! I don't checked already the "global" hook.
Where is this in the src?
Futhermore, can you add a setting option (like "Hardcoded values" and "Debug Mode") for "Global Settings"? This will override the list of "Specific App" and will hook all packages.

You agree?

**Comment by bigsinger** [comment]
good idea

**Comment by lars18th** [comment]
> good idea

Great. So, please add it to the TODO #31 .
