### ISSUE TITLE
Core: Split preferences values

### ISSUE THREAD

**Issue by lars18th** [bigsinger/AndroidIdChanger#34]
Hi,

At time, the file "CHANGER.xml" has two types of values:

1. General settings, like "hook_all_app", "debug_mode" and "use_hardcoded_value".
2. Values to hook, like "IMEI", "SerialNo", "CODENAME", etc.

I suggest to move the values of type 2 to the "phoneinfo.xml" as it will be more consistent.
You agree?

Futhermore, I want to know if the file "com.bigsing.changer.BETA_VALUES.xml" it's really necessary. Perhaps the content can be incorporated to "CHANGER.xml" (even "ThemeColor.xml" too). The idea is have one file for App config, and one file for Hooks config.

**Comment by bigsinger** [comment]
i've not written"IMEI", "SerialNo", "CODENAME" in "CHANGER.xml"

com.bigsing.changer.BETA_VALUES.xml is not necessary

**Comment by lars18th** [comment]
> com.bigsing.changer.BETA_VALUES.xml is not necessary

But, the file exists! Please, remove it from the project then.

> i've not written"IMEI", "SerialNo", "CODENAME" in "CHANGER.xml"

This is the current content of my "CHANGER.xml":

```
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <boolean name="SimState" value="false" />
    <boolean name="Resolution" value="false" />
    <boolean name="googlead_id" value="false" />
    <boolean name="hook_all_app" value="false" />
    <boolean name="IP" value="false" />
    <boolean name="WifiBssid" value="false" />
    <string name="packages"> flar2.devcheck</string>
    <boolean name="WifiMac" value="false" />
    <boolean name="Wifissid" value="false" />
    <boolean name="SimOperator" value="false" />
    <boolean name="SerialNo" value="true" />
    <boolean name="Width" value="false" />
    <boolean name="NetType" value="false" />
    <boolean name="SimCountryIso" value="false" />
    <boolean name="BluetoothMac" value="false" />
    <boolean name="NetworkOperatorName" value="false" />
    <boolean name="use_hardcoded_value" value="false" />
    <boolean name="debug_mode" value="true" />
    <boolean name="AndroidId" value="false" />
    <boolean name="PhoneNumber" value="false" />
    <boolean name="SimSerialNo" value="false" />
    <boolean name="Height" value="false" />
    <boolean name="SimOperatorName" value="false" />
    <boolean name="SubscriberId" value="false" />
</map>
```

My suggestion it's move all hook values for enable/disable to the "phoneinfo.xml" file. In this file you can put the hooked values and if it's enabled or not. And leave inside "CHANGER.xml" only values for the App.

It will be more clear!

**Comment by bigsinger** [comment]
`<boolean name="SimState" value="false" />`
...


this values are for UI but not logic.

in phoneinfo.xml we set empty value when we unchecking the checkbox before the item.

**Comment by lars18th** [comment]
Hi @bigsinger ,

> this values are for UI but not logic.
> in phoneinfo.xml we set empty value when we unchecking the checkbox before the item.

This is annoying. You don't need to use "redundant" data. Or use the boolean, or use the empty value; but not both. If you use both some inconsistence can appear!

My suggestion is this (select the option you prefer):

1. Move all boolean values like "SimState" from "CHANGER.xml" to "phoneinfo.xml". Then use this value for both the UI and the hooking.

2. Or remove these boolean values from "CHANGER.xml" and check only the "phoneinfo.xml" for setting the enable/disable in the UI.

What you prefer?

**Comment by bigsinger** [comment]
I want to know what it means to do this

**Comment by lars18th** [comment]
> I want to know what it means to do this

OK. I explain in detail...

At time, you save some values in the file "CHANGER.xml" only to know if one value is active or disabled. One example is "< boolean name="PhoneNumber" value="false" /> ". However, these values are not related to the _CONFIGURATION_ of the APP. The values directly related to the config are only this (at time, perhaps in the future some others are added):

```
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <boolean name="hook_all_app" value="false" />
    <string name="packages"> flar2.devcheck</string>
    <boolean name="use_hardcoded_value" value="false" />
    <boolean name="debug_mode" value="true" />
</map>
```

I suggest to remove all other values from this file, and use the "empty" value in "phoneinfo.xml" as a trigger for the enable/disable toggle in the UI.

Are now more clear? :smile:

**Comment by bigsinger** [comment]
but in the phoneinfo.xml file, it'll be: 
`<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <boolean name="SimState" value="false" />
    <string name="SimState" value="1" />
</map>`



means one key will appear twice

**Comment by lars18th** [comment]
> means one key will appear twice

Not if you remove the "boolean" and use the value="". Or just change the vluer="" in your code with the "boolean" (however, this can be a bad idea if the preferences can't be readed. I prefer to continue using the "null" as "disable").

In any case, you don't want to touch a lot of the code, then simple "repeat" (twice appear) in the "phoneinfo.xml". This isn't an error!
