### ISSUE TITLE
Android 7.0 框架提示未启用

### ISSUE THREAD

**Issue by imoldchen** [bigsinger/AndroidIdChanger#36]
在7.0下（手机／平板）不点击随机就无法修改保存（可视化编辑），实际点保存查看xml文件是写入了的，但是在修改的时候选择修改某栏信息，再切换到其他栏目的时候，会丢失或者填入信息变成之前其他栏目填写的内容。

**Comment by bigsinger** [comment]
点完随机后直接去点保存。
手动修改数值目前还有BUG。
