### ISSUE TITLE
version:1.4 使用过程中的几点建议 

### ISSUE THREAD

**Issue by 16016128** [bigsinger/AndroidIdChanger#4]
1.导入导出机型信息,因为这些信息可能不是使用一次;
2.给开发者预留某个接口,如:上传机型信息后,adb广播以生效;
--以上纯属个人建议;
如果可以的话,我愿意资助作者

**Comment by 3c** [comment]
生成的信息都在xml里，你可以直接去读 ， 如果root了，也可以去写

**Comment by 16016128** [comment]
您好:
我希望实现以下需求,
基于xposed框架开发的模块

1.修改安卓设备机型,修改项至少包含如下:
	1.1 IMEI;
	1.2 IMSI
	1.3 android
	1.4 手机号;
	1.5 手机卡序列号
	1.6 运营商代码;
	1.7 运营商名字(中国联通/移动/电信)
	1.8 MAC地址;
	1.9 无线路由器名称;
	2.0 无线路由器地址;
	2.1 屏幕分辨率
	2.2 品牌
	2.3 型号
	2.4 产品名称(与型号值相同)
	2.5 制造商(品牌相同)
	2.6 设备名(品牌相同)
	2.7 CPU型号;
	2.8 指纹型号
	2.9 串口序号;
	3.0 显卡型号;
2.屏蔽某APP检测某APP,如:屏蔽QQ检测xposed框架;

3.软件不需要图形界面,从本地文件读取配置信息,并修改;
  如:PC上传device.txt(包含设备信息的json)到SDcard,并通过adb 发送一条广播,APP这时候进行机型修改;

4.PC上传的json配置信息,必须包含sign签名,如:根据某些值,某些时间来校验,校验通过,则执行机型修改,否则返回;

如果您有时间定制这个模块,可以联系我:
QQ:16016128
TEL:13121614111
MAIL:16016128@QQ.COM

TKS

**Comment by lars18th** [comment]
Hi,

I feel all suggestions are now implement. Only remains the option for "import/export" the hook values. This is equal to the issue #1. One option for "export" the "phoneinfo.xml" to the SDCard and "import" it will be valuable.

I suggest close this issue and continue in the #1 for the import/export.

**Comment by ikyak** [comment]
Recent update doesn't hook my specific apps, where should I download previous version?

**Comment by bigsinger** [comment]
https://github.com/bigsinger/AndroidIdChanger/tree/master/release
