### ISSUE TITLE
已经有导出功能，能不能加入导入功能

### ISSUE THREAD

**Issue by g5509889** [bigsinger/AndroidIdChanger#40]
希望增加导入功能

**Comment by bigsinger** [comment]
怎么个使用法？

**Comment by g5509889** [comment]
把已设置的信息导出到文件，需要的时候可以把这个信息从文件导入到软件

**Comment by bigsinger** [comment]
现在不也可以吗

**Comment by g5509889** [comment]
只找到了“导出设备信息到文件并分享”选项，并没发现导入选项，请问在哪里可以找到，另外建议可以有选择的随机部分信息，比如打钩的，点随机可以变化，没打钩的保持原有信息，另外点随机后部分信息变为空白，有时点保存修改，信息会错位，比如手机号会变成WiFiSSID里的信息，是不是bug，感谢阅读

**Comment by bigsinger** [comment]
1、直接替换掉shared_prefs下的xml文件即可。
2、不打勾的虽然随机，但是不会生效，运行时不会修改其数值的。
3、错位的BUG好像修复了，升级到最新版即可。
