### ISSUE TITLE
能否加一个白名单的功能

### ISSUE THREAD

**Issue by heartsation** [bigsinger/AndroidIdChanger#41]
大部分程序都可以正常hook,但是有极个别的无法使用，比如说网易云音乐，请问一下能否改一下过滤规则，添加进去不被hook

**Comment by bigsinger** [comment]
> 大部分程序都可以正常hook,但是有极个别的无法使用，比如说网易云音乐，请问一下能否改一下过滤规则，添加进去不被hook

那就不要添加进去呗。
