### ISSUE TITLE
希望增加一项设置参数 characteristics

### ISSUE THREAD

**Issue by imoldchen** [bigsinger/AndroidIdChanger#45]
ro.build.characteristics
这个参数默认为 default，可以修改为平板、手机、电视三种模式:tablet/phone/tv, 默认是手机模式,配合density 修改 dpi 和机型来解除 Google Play 市场对目标平台的下载限制，有些手机App在平板和电视上不给下载，实际是可以安装使用的。

另外，能不能给不同app指定不同的配置呢?

**Comment by bigsinger** [comment]
不同app指定不同的配置是有的，在设置里。
