### ISSUE TITLE
Crumble the app

### ISSUE THREAD

**Issue by Debweb86** [bigsinger/AndroidIdChanger#47]
Hi. After installing the module . Other applications refuse to start . Such as OpenVPN and some others . How to fix ?please tell me

**Comment by nihadnagi** [comment]
### **1. Click the Menu, goto SETTINGS**

![screenshot_20180822-082222](https://user-images.githubusercontent.com/6548782/44436010-24cddb80-a5b3-11e8-99d3-102a517a60a8.png)

### **2. Make Sure to UNCHECK the "Hook All Apps, so you can exclude the ones that don't violate your privacy, in your case, OpenVPN or any other VPN would need access to real physical or virtual addresses.** 


![screenshot_20180822-082328](https://user-images.githubusercontent.com/6548782/44436031-3adb9c00-a5b3-11e8-8369-e0e918743334.png)


### **3. Now, goto Specific Apps from the Menu.**

![screenshot_20180822-082222](https://user-images.githubusercontent.com/6548782/44436010-24cddb80-a5b3-11e8-99d3-102a517a60a8.png)

### **4. Now, this list the apps installed, and which you want to hook on the spoof and which is not. If they are in BLACK like below, then they are excluded from the spoofing hooks. The reason, the app itself is in black. But, let's try to add the Changer app itself to the spoofing hooks, by LONG pressing it, and clicking Add/Remove to Hook List**




![screenshot_20180822-082459](https://user-images.githubusercontent.com/6548782/44436065-63639600-a5b3-11e8-9419-ffa188c88f95.png)




### **5. You will get the following message.**





![screenshot_20180822-082522](https://user-images.githubusercontent.com/6548782/44436080-78402980-a5b3-11e8-87c8-d3ead4b1b077.png)



### **6. So, now, let's assume that we want to include the Xposed Framework to the Spoofing hooks, LONG press, and click "Add/Remove to Hook List", this will mark it in Red as shown. Never do it, this will crash the framework and hence the changer app.**


![screenshot_20180822-082558](https://user-images.githubusercontent.com/6548782/44436083-7aa28380-a5b3-11e8-8e13-344eb320f7d0.png)

### **Hope this helps**


**@bigsinger Kindly, give the read-only to the framework too, if the framework, the container of the app can get added to the child spoof list, it will crash and so will the app.**

**Comment by bigsinger** [comment]
you can use the version:1.24
