### ISSUE TITLE
为什么随机SDK版本一直低于19

### ISSUE THREAD

**Issue by thinkworld0** [bigsinger/AndroidIdChanger#48]
可不可以随机SDK版本大于19怎么设置？

**Comment by bigsinger** [comment]
随机是按照这个数组对应添加更新的，要么你来多添加几组？我是懒得添加了。

    public static int[] sdkVersionArr = new int[]{15, 15, 16, 16, 17, 17, 18, 18, 19, 19, 19, 15, 15, 16, 16, 17, 17, 18, 18, 19, 19, 19, 15, 15, 16, 16, 17, 17, 18, 18, 19, 19, 19, 15, 15, 16, 16, 17, 17, 18, 18, 19, 19, 19, 15, 15, 16, 16, 17, 17, 18, 18, 19, 19, 19, 15, 15, 16, 16, 17, 17, 18, 18, 19, 19, 19, 15, 15, 16, 16, 17, 17, 18, 18, 19, 19, 19, 15, 15, 16, 16, 17, 17, 18, 18, 19, 19, 19};

    public static String[] releaseArray = new String[]{"4.0.3", "4.0.4", "4.1.1", "4.1.2", "4.2.1", "4.2.2", "4.3", "4.3.1", "4.4.2", "4.4.3", "4.4.4", "4.0.3", "4.0.4", "4.1.1", "4.1.2", "4.2.1", "4.2.2", "4.3", "4.3.1", "4.4.2", "4.4.3", "4.4.4", "4.0.3", "4.0.4", "4.1.1", "4.1.2", "4.2.1", "4.2.2", "4.3", "4.3.1", "4.4.2", "4.4.3", "4.4.4", "4.0.3", "4.0.4", "4.1.1", "4.1.2", "4.2.1", "4.2.2", "4.3", "4.3.1", "4.4.2", "4.4.3", "4.4.4", "4.0.3", "4.0.4", "4.1.1", "4.1.2", "4.2.1", "4.2.2", "4.3", "4.3.1", "4.4.2", "4.4.3", "4.4.4", "4.0.3", "4.0.4", "4.1.1", "4.1.2", "4.2.1", "4.2.2", "4.3", "4.3.1", "4.4.2", "4.4.3", "4.4.4", "4.0.3", "4.0.4", "4.1.1", "4.1.2", "4.2.1", "4.2.2", "4.3", "4.3.1", "4.4.2", "4.4.3", "4.4.4", "4.0.3", "4.0.4", "4.1.1", "4.1.2", "4.2.1", "4.2.2", "4.3", "4.3.1", "4.4.2", "4.4.3", "4.4.4"};

    public static String[] resolution_randomArray = new String[]{"Huawei&H30-T00&1280&720&MT6582", "Huawei&HN3-U01&1280&720&MSM8916", "HTC&D820u&1280&720&MSM8939", "Coolpad&8675-HD&1280&720&MT6592", "Lenovo&S90-T&1280&720&MSM8916", "Huawei&G750-T01&1280&720&MT6592M", "Samsung&I939D&1280&720&Exynos 4412", "SAMSUNG&GT-N7100&1280&720&Exynos 4412", "Lenovo&A808T&1280&720&MT6592", "Huawei&G750-T00&1280&720&MT6592", "OPPO&R6007&1280&720&MSM8928", "ZTE&N9180&1280&720&MSM8926", "Lenovo&S898T+&1280&720&MT6592", "Huawei&H30-T00&1280&720&MT6582", "Huawei&HN3-U01&1280&720&MSM8916", "HTC&D820u&1280&720&MSM8939", "Coolpad&8675-HD&1280&720&MT6592", "Lenovo&S90-T&1280&720&MSM8916", "Huawei&G750-T01&1280&720&MT6592M", "Samsung&I939D&1280&720&Exynos 4412", "SAMSUNG&GT-N7100&1280&720&Exynos 4412", "Lenovo&A808T&1280&720&MT6592", "Huawei&G750-T00&1280&720&MT6592", "OPPO&R6007&1280&720&MSM8928", "ZTE&N9180&1280&720&MSM8926", "Lenovo&S898T+&1280&720&MT6592", "Huawei&H30-T00&1280&720&MT6582", "Huawei&HN3-U01&1280&720&MSM8916", "HTC&D820u&1280&720&MSM8939", "Coolpad&8675-HD&1280&720&MT6592", "Lenovo&S90-T&1280&720&MSM8916", "Huawei&G750-T01&1280&720&MT6592M", "Samsung&I939D&1280&720&Exynos 4412", "SAMSUNG&GT-N7100&1280&720&Exynos 4412", "Lenovo&A808T&1280&720&MT6592", "Huawei&G750-T00&1280&720&MT6592", "OPPO&R6007&1280&720&MSM8928", "ZTE&N9180&1280&720&MSM8926", "Lenovo&S898T+&1280&720&MT6592", "Lenovo&A320T&800&480&MSM8674AB", "Lenovo&A670t&800&480&MSM8674AB", "Lenovo&A396&800&480&MSM8674AB", "Lenovo&A238T&800&480&MSM8674AB", "Lenovo&A690&800&480&MSM8674AB", "Samsung&SM-G3589W&800&480&MSM8674AB", "Samsung&GT-S7562i&800&480&APQ8060", "Samsung&SCH-I679&800&480&MSM8674AB", "Samsung&GT-S7898I&800&480&MSM8674AC", "Samsung&GT-S7572&800&480&APQ8060", "Samsung&S7568&800&480&MSM8674AB", "Coolpad&8122&800&480&Nvidia Tegra 4", "Coolpad&5860S&800&480&MT6592", "Coolpad&5217&800&480&Nvidia Tegra 4", "Coolpad&7060&800&480&MT6592", "K-Touch&W656&800&480&MSM8974AB", "K-Touch&W68&800&480&MSM8974AA", "K-Touch&T780&800&480&MT6592H", "K-Touch&L820&800&480&MT6592", "HTC&D610T&854&480&MT6592", "HTC&D310W&854&480&APQ8060", "K-Touch&Tou ch 2&854&480&MT6592", "Huawei&Y600D-C00&854&480&MT6592", "ZTE&Q505T&854&480&MSM8974AB", "ZTE&N919D&854&480&MSM8974AB", "Samsung&Galaxy S4 Zoom&960&540&MSM8674AB", "Samsung&I9158&960&540&MSM8674AB", "Huawei&C8816&960&540&Snapdragon600", "Huawei&C8816&960&540&MSM8674AB", "Sony&S39h&960&540&MT6589", "Huawei&G6&960&540&MT6582M", "HTC&7088&960&540&SC8735s", "Samsung&P709&960&540&MSM8674AB", "Coolpad&8079&480&320&SC8825", "Philips&T939&480&320&MSM8674AB", "vivo&Y1&480&320&MSM8674AB", "vivo&Y3t&480&320&MSM8674AB", "Coolpad&8076&480&320&SC8810T", "Lenovo&A320T&800&480&MSM8674AB", "Lenovo&A670t&800&480&MSM8674AB", "Lenovo&A396&800&480&MSM8674AB", "Lenovo&A238T&800&480&MSM8674AB", "Lenovo&A690&800&480&MSM8674AB", "Samsung&SM-G3589W&800&480&MSM8674AB", "Samsung&GT-S7562i&800&480&APQ8060", "Samsung&SCH-I679&800&480&MSM8674AB", "Samsung&GT-S7898I&800&480&MSM8674AC", "Samsung&GT-S7572&800&480&APQ8060", "Samsung&S7568&800&480&MSM8674AB", "Coolpad&8122&800&480&Nvidia Tegra 4", "Coolpad&5860S&800&480&MT6592", "Coolpad&5217&800&480&Nvidia Tegra 4", "Coolpad&7060&800&480&MT6592", "K-Touch&W656&800&480&MSM8974AB", "K-Touch&W68&800&480&MSM8974AA", "K-Touch&T780&800&480&MT6592H", "K-Touch&L820&800&480&MT6592", "HTC&D610T&854&480&MT6592", "HTC&D310W&854&480&APQ8060", "K-Touch&Tou ch 2&854&480&MT6592", "Huawei&Y600D-C00&854&480&MT6592", "ZTE&Q505T&854&480&MSM8974AB", "ZTE&N919D&854&480&MSM8974AB", "Samsung&Galaxy S4 Zoom&960&540&MSM8674AB", "Samsung&I9158&960&540&MSM8674AB", "Huawei&C8816&960&540&Snapdragon600", "Huawei&C8816&960&540&MSM8674AB", "Sony&S39h&960&540&MT6589", "Huawei&G6&960&540&MT6582M", "HTC&7088&960&540&SC8735s", "Samsung&P709&960&540&MSM8674AB", "Coolpad&8079&480&320&SC8825", "Philips&T939&480&320&MSM8674AB", "vivo&Y1&480&320&MSM8674AB", "vivo&Y3t&480&320&MSM8674AB", "Coolpad&8076&480&320&SC8810T"};
