### ISSUE TITLE
xposed开启插件后, 保存配置, 重启机器, 配置没有重读?

### ISSUE THREAD

**Issue by zeroleo12345** [bigsinger/AndroidIdChanger#6]
xposed开启插件后, 保存配置, 重启机器后, 打开软件看到还是修改前的参数~
不是真机, 使用夜神模拟器

**Comment by aaaaasuper** [comment]
我也是啊，两台手机都这样，最好能改成2个标签，一个是机器配置，一个是修改后的配置。

**Comment by lars18th** [comment]
Hi,

This is already fixed! :smile: 
Please, close the issue.
