### ISSUE TITLE
应用修改后部分应用被屏蔽

### ISSUE THREAD

**Issue by aaaaasuper** [bigsinger/AndroidIdChanger#64]
对一个应用修改ID后，这个应用就无法获得包名含有xposed的应用了
 就是一个app本来没修改id前，可以查看所有应用，但是修改后，这个app获得的应用列表就不全了
所有包名含有xposed的和名称含有xposed对这个应用都不可见了。
 应用隐藏有更好的工具，不希望隐藏这些应用，或者给一个开关，我可以关闭这个功能。
 希望作者改改进这个功能，一个开关应该好改吧。

**Comment by studio888** [comment]
推荐个"隐藏应用"的好工具啦, 谢谢

**Comment by aaaaasuper** [comment]
hideapp

> 推荐个"隐藏应用"的好工具啦, 谢谢


hideapp 要5.4版本的，支持8.0以下系统，不含8.0，基于xposed，有各种模板，配置错了隐藏系统应用都有可能不开机。

还有个dotmod 也挺好 也是xposed 应用级的，但是没模板，用起来不方便

**Comment by bigsinger** [comment]
> 对一个应用修改ID后，这个应用就无法获得包名含有xposed的应用了
> 就是一个app本来没修改id前，可以查看所有应用，但是修改后，这个app获得的应用列表就不全了
> 所有包名含有xposed的和名称含有xposed对这个应用都不可见了。
> 应用隐藏有更好的工具，不希望隐藏这些应用，或者给一个开关，我可以关闭这个功能。
> 希望作者改改进这个功能，一个开关应该好改吧。

故意隐藏了xposed
