### ISSUE TITLE
老铁，请问一下有个guid的参数可以hook么。

### ISSUE THREAD

**Issue by Lockey-J** [bigsinger/AndroidIdChanger#67]
手机里有个guid。这一个能不能在软件里加这个功能呢。

**Comment by bigsinger** [comment]
> 手机里有个guid。这一个能不能在软件里加这个功能呢。

哪个guid?

**Comment by Lockey-J** [comment]
想kingroot 里查看硬件参数里就有这个，我们可以查看到手机guid 这个值
