### ISSUE TITLE
Support for each app separately

### ISSUE THREAD

**Issue by doomlord77** [bigsinger/AndroidIdChanger#68]
Can you make it possible to set custom values for each app individually? It's not very usable with only global settings.

您是否可以单独为每个应用设置自定义值？仅在全局设置下它不是很有用。

**Comment by HamidZaeri** [comment]
Yes, exactly.
It is good to make a profile for each app.

**Comment by bigsinger** [comment]
> Can you make it possible to set custom values for each app individually? It's not very usable with only global settings.
> 
> 您是否可以单独为每个应用设置自定义值？仅在全局设置下它不是很有用。



> Yes, exactly.
> It is good to make a profile for each app.

功能在设置（settings）里有的，可以打开体验。

**Comment by doomlord77** [comment]
Thanks!

**Comment by HamidZaeri** [comment]
Current settings is to select some apps to be hooked, and all of them with only one profile.
but I meant, set different settings for each app. (like different imei for different apps)

My suggestion is that we can create new profiles (which contains specific imei, serial, ...)
and then choose apps to be spoofed by that profile.
