### ISSUE TITLE
在安卓模拟器上无法使用

### ISSUE THREAD

**Issue by chengyikan** [bigsinger/AndroidIdChanger#69]
能不能留下个联系方式,他在安卓模拟器上运行正常但是修改信息没有起到作用.
希望能联系上您。我的TG:BrushBrush

**Comment by bigsinger** [comment]
> 能不能留下个联系方式,他在安卓模拟器上运行正常但是修改信息没有起到作用.
> 希望能联系上您。我的TG:BrushBrush

可以在模拟器上使用，具体是什么模拟器？

**Comment by chengyikan** [comment]
逍遥模拟器。安装是能信息也变化就是对于应用不启做用，APP应该没有变化

**Comment by chengyikan** [comment]
能定制吗？我想定制一套在逍遥模拟器上使用,

**Comment by yigenren** [comment]
在virtualxposed中不起作用。

**Comment by bigsinger** [comment]
> 在virtualxposed中不起作用。

你用的哪个版本？

**Comment by yigenren** [comment]
Virtualxposed_0.17.1

**Comment by bigsinger** [comment]
AndroidIdChanger呢

**Comment by yigenren** [comment]
v1.24

**Comment by bigsinger** [comment]
https://github.com/bigsinger/AndroidIdChanger/tree/master/release
用下历史版本试试看

**Comment by yigenren** [comment]
v1.24
