### ISSUE TITLE
能定制吗？我想定制一套在逍遥模拟器上使用。

### ISSUE THREAD

**Issue by chengyikan** [bigsinger/AndroidIdChanger#70]
我测试的时候，他能做逍遥模拟器上正常工作.但是APP应用不能读取修改的配置信息.

**Comment by bigsinger** [comment]
> 我测试的时候，他能做逍遥模拟器上正常工作.但是APP应用不能读取修改的配置信息.

实测可以在逍遥模拟器上使用，如需定制可以私聊。

**Comment by chengyikan** [comment]
QQ多少
