### ISSUE TITLE
Can't apply the values System Wide

### ISSUE THREAD

**Issue by huuchi207** [bigsinger/AndroidIdChanger#71]
When I press button Random, the message showed: "Already saved! But No App Specified. Please specify App in [Specific App], Long Press App in Apps List".
How can I apply the values System Wide? And How can I check if the device information has changed(example when I entered new IMEI value)
![973e86fb-0063-4124-9a8b-4c51b4154373](https://user-images.githubusercontent.com/25658269/51789017-0057da00-21b7-11e9-8504-bce573f8e87f.png)

**Comment by bigsinger** [comment]
- 不支持全局HOOK

- 可以使用1.24版本很方便地指定APP：https://github.com/bigsinger/AndroidIdChanger/blob/master/release/1.24.apk
