### ISSUE TITLE
GoogleAdID 修改无效

### ISSUE THREAD

**Issue by lieren16** [bigsinger/AndroidIdChanger#73]
测试了下，修改gaid 无效啊，需要重启？

**Comment by bigsinger** [comment]
你试试1.24版本https://github.com/bigsinger/AndroidIdChanger/blob/master/release/1.24.apk

**Comment by dingyangfan** [comment]
还是失效的

**Comment by bigsinger** [comment]
怎么验证呢 给个apk测测

**Comment by dingyangfan** [comment]
https://play.google.com/store/apps/details?id=com.appsflyer.android.deviceid
https://play.google.com/store/apps/details?id=my.android.version
如果用不了 可以来这里下载

**Comment by dingyangfan** [comment]
https://apkpure.com/cn/my-device-ids/my.android.version
https://apkpure.com/cn/my-device-id-by-appsflyer/com.appsflyer.android.deviceid
