### ISSUE TITLE
更改ua头信息

### ISSUE THREAD

**Issue by dingyangfan** [bigsinger/AndroidIdChanger#75]
能不能加入一个更改系统默认浏览器头信息的功能，chrome的也行呀。感觉你的很完善了，加上界面可以收费了。

**Comment by bigsinger** [comment]
你用的哪个版本

**Comment by dingyangfan** [comment]
1.9.apk   在一个网站下载的，用完以后黑屏了，，是不是修改了硬件编码？

**Comment by bigsinger** [comment]
https://github.com/bigsinger/AndroidIdChanger/tree/master/release
可以试试1.24版本
