### ISSUE TITLE
1.24版本配置imei无效

### ISSUE THREAD

**Issue by happyaguang** [bigsinger/AndroidIdChanger#79]
升级了1.24之后 右上角没有save按钮了。修改imei也没有效果。导致我部分app不能使用（app发现imei变化，不让登录）。系统是 lineageos 14。

**Comment by joeycold** [comment]
@happyaguang 你的系统版本是多少啊？就只是imei改不掉么？

**Comment by bigsinger** [comment]
需要制定app
