### ISSUE TITLE
为什么修改信息保存后信息不变，，就算重启还是没变，，软件根本就没有申请root权限

### ISSUE THREAD

**Issue by FlameskyDexive** [bigsinger/AndroidIdChanger#8]
为什么修改信息保存后信息不变，，就算重启还是没变，，软件根本就没有申请root权限，，是不是软件本身的问题啊？我在MIUI6和Flyme6都测试了，，都不行

**Comment by lars18th** [comment]
Hi @FlameskyDexive ,

This is already reported. See #30.

Please, continue in this other thread and close this. :smile:
