### ISSUE TITLE
Want to Buy the Source Code 

### ISSUE THREAD

**Issue by ImCowboySibs** [bigsinger/AndroidIdChanger#90]
Hi I would like to buy the applications source code from you, but I am unable to send messages via Weibo

**Comment by bigsinger** [comment]
pushebp#163.com

**Comment by ImCowboySibs** [comment]
Hi, I sent you an Email, please reply when you have time.

Thank You

**Comment by bigsinger** [comment]
> Hi, I sent you an Email, please reply when you have time.
> 
> Thank You

@ImCowboySibs

replied
